# ------------------------------------------------------------------------
# Copyright (c) 2022 Woon-Ha Yeo <woonhahaha@gmail.com>.
# Copyright (c) 2022 Wang-Taek Oh <mm0741@naver.com>.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: EnsembleNet-nb3
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 36

datasets:
  train:
    name: iffi-train
    type: PairedNpyImageDataset
    dataroot_gt: ./datasets/IFFI/train/target_ensemble
    dataroot_lq: ./datasets/IFFI/train_ensemble/input
    
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

network_g:
  type: EnsembleNet
  width: 32
  ens_num: 3 # number of ensemble models
  blk_num: 3 # number of NAFBlocks
  tta: False

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500