# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: CISR_NAFLSR-B_x4_Crop256
model_type: ImageRestorationModel
scale: 4
num_gpu: 4
manual_seed: 42

datasets:
  train:
    name: CISR-train
    type: PairedImageDataset
    dataroot_gt: datasets/CISR/train/target_crops.lmdb
    dataroot_lq: datasets/CISR/train/input_crops.lmdb
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: false
    flip_RGB: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: NAFLSR
  up_scale: 4
  width: 96
  num_blks: 64
  drop_path_rate: 0.2
  drop_out_rate: 0.

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 3e-3
    weight_decay: !!float 0
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up
  mixup: false

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.
    reduction: mean

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: AIM2022-CISR
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
